# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4da87475f00241adf0f001eee6c2c54d8b866dec44fd23ac4f95a33e18f6f2ab7cf037b2a2b1936e8bbbad9c87c0a450f4bd3fb861340654a1c18ac37ddf144

test:
  secret_key_base: 8c841a00c258f08fbb1c6887ecbe815fc81e7b8abf71f0fece044731b0f3e1478f8fbd35700a4489e78139b1a74644f4e875c05b4a8bd91a062226d61f28ce9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
